# Public Domain (-) 2026-present, The Espra Core Authors.
# See the Espra Core UNLICENSE file for details.

import os
import sys
import urllib.request

DEBUG = "-d" in sys.argv


def exit(msg):
    print(f"\033[31m!! ERROR: {msg} !!\033[0m")
    sys.exit(1)


def fetch(url, build_dir, filename=None, leading_newline=True):
    if not os.path.exists(build_dir):
        os.makedirs(build_dir)
    if filename is None:
        filename = url.split("/")[-1]
    filepath = os.path.join(build_dir, filename)
    newline = "\n" if leading_newline else ""
    if os.path.exists(filepath):
        print(f"{newline}>> Reading {filename} from cache ...")
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    print(f"{newline}>> Downloading {url} ...")
    with urllib.request.urlopen(url) as resp:
        data = resp.read()
        with open(filepath, "wb") as f:
            f.write(data)
        return data.decode("utf-8")


def write_file(lines, filepath):
    output = "\n".join(lines)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(output)
    print(f"\n>> Generated {filepath}")


def zig_file(*modules):
    lines = []
    script_name = os.path.basename(sys.argv[0])
    out = lines.append
    out("// !! DO NOT EDIT !!")
    out(f"// This file was auto-generated by tool/{script_name}")
    out("")
    if modules:
        for module in modules:
            out(f'const {module} = @import("{module}");')
        out("")
    return lines, out
